/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"fmt"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// Strength - summary: signal strength
func (s *DefaultApiService) Strength(ctx context.Context, body StrengthInput) (ImplResponse, error) {
	strength_float := body.computeStrength()
	outputStrengthOutput := StrengthOutput{
		body.Expected,
		body.Actual,
		strength_float,
	}

	fmt.Println("Expected=", body.Expected)
	fmt.Println("Actual=", body.Actual)
	fmt.Println("strength_float=", strength_float)

	return Response(200, outputStrengthOutput), nil

}
