/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StrengthInput struct {

	Actual int32 `json:"actual,omitempty"`

	Expected int32 `json:"expected,omitempty"`
}

// signal strength
func (s StrengthInput) computeStrength() float32 {
	return float32(s.Actual) / float32(s.Expected)
}