openapi: 3.0.1
info:
  title: Signal Strength
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: https://wilsonify.github.io/
  url: https://wilsonify.github.io/
servers:
- url: //localhost/
paths:
  /strength:
    post:
      summary: 'summary: signal strength'
      description: 'description: signal strength'
      operationId: strength
      requestBody:
        description: actual vs expected counts
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/strength-input'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/strength-output'
        400:
          description: Known Error
          content: {}
        500:
          description: Unknown Error
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    strength-input:
      type: object
      properties:
        actual:
          type: integer
        expected:
          type: integer
    strength-output:
      type: object
      properties:
        actual:
          type: integer
        expected:
          type: integer
        strength:
          type: number
