openapi: 3.0.1
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Signal Strength
  version: 1.0.0
externalDocs:
  description: https://wilsonify.github.io/
  url: https://wilsonify.github.io/
servers:
- url: //localhost/
paths:
  /strength:
    post:
      description: 'description: signal strength'
      operationId: strength
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/strength-input'
        description: actual vs expected counts
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/strength-output'
          description: Success
        "400":
          content: {}
          description: Known Error
        "500":
          content: {}
          description: Unknown Error
      summary: 'summary: signal strength'
      x-codegen-request-body-name: body
components:
  schemas:
    strength-input:
      properties:
        actual:
          type: integer
        expected:
          type: integer
      type: object
    strength-output:
      example:
        actual: 0
        strength: 1.4658129805029452
        expected: 6
      properties:
        actual:
          type: integer
        expected:
          type: integer
        strength:
          type: number
      type: object
