/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StrengthOutput struct {

	Actual int32 `json:"actual,omitempty"`

	Expected int32 `json:"expected,omitempty"`

	Strength float32 `json:"strength,omitempty"`
}
