/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

// Strength - summary: signal strength
func Strength(c *gin.Context) {
	var inputStrengthInput StrengthInput
	c.BindJSON(&inputStrengthInput)

	strength_float := inputStrengthInput.computeStrength()
	outputStrengthOutput := StrengthOutput{
		inputStrengthInput.Expected,
		inputStrengthInput.Actual,
		strength_float,
	}

	fmt.Println("Expected=", inputStrengthInput.Expected)
	fmt.Println("Actual=", inputStrengthInput.Actual)
	fmt.Println("strength_float=", strength_float)

	c.JSON(http.StatusOK, outputStrengthOutput)
}
