/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StrengthInput struct {

	Actual int32 `json:"actual,omitempty"`

	Expected int32 `json:"expected,omitempty"`
}

// AssertStrengthInputRequired checks if the required fields are not zero-ed
func AssertStrengthInputRequired(obj StrengthInput) error {
	return nil
}

// AssertRecurseStrengthInputRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StrengthInput (e.g. [][]StrengthInput), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStrengthInputRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStrengthInput, ok := obj.(StrengthInput)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStrengthInputRequired(aStrengthInput)
	})
}
