/*
 * Signal Strength
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type StrengthOutput struct {

	Actual int32 `json:"actual,omitempty"`

	Expected int32 `json:"expected,omitempty"`

	Strength float32 `json:"strength,omitempty"`
}

// AssertStrengthOutputRequired checks if the required fields are not zero-ed
func AssertStrengthOutputRequired(obj StrengthOutput) error {
	return nil
}

// AssertRecurseStrengthOutputRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StrengthOutput (e.g. [][]StrengthOutput), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStrengthOutputRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStrengthOutput, ok := obj.(StrengthOutput)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStrengthOutputRequired(aStrengthOutput)
	})
}
